# Generated by Django 6.0.1 on 2026-04-09 18:38

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdocument',
            name='file',
            field=models.FileField(upload_to=api.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['txt', 'md'])]),
        ),
    ]
